"""Add payment_status and refund_id to orders

Revision ID: 106f80147634
Revises: fa4c90a3087f
Create Date: 2024-11-27 12:40:00.439888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106f80147634'
down_revision = 'fa4c90a3087f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refund_id', sa.String(length=100), nullable=True))
        
    # Update existing rows with default payment_status
    op.execute("UPDATE orders SET payment_status = 'paid' WHERE status = 'paid'")
    op.execute("UPDATE orders SET payment_status = 'pending' WHERE status != 'paid'")
    
    # Now make payment_status NOT NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
                            existing_type=sa.String(length=20),
                            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('refund_id')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
