"""Add shipping carrier and method models

Revision ID: 58c649cf7f5e
Revises: a91a2f3aa387
Create Date: 2024-12-12 02:33:34.725331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c649cf7f5e'
down_revision = 'a91a2f3aa387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('default_location_id', sa.String(length=100), nullable=True),
    sa.Column('default_location_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_carrier_code')
    )
    op.create_table('shipping_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_days', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['shipping_carriers.id'], name='fk_method_carrier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('quote_data', sa.JSON(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['shipping_carriers.id'], name='fk_quote_carrier'),
    sa.ForeignKeyConstraint(['method_id'], ['shipping_methods.id'], name='fk_quote_method'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_quote_order'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_carrier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_method_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_shipping_method', 'shipping_methods', ['shipping_method_id'], ['id'])
        batch_op.create_foreign_key('fk_order_shipping_carrier', 'shipping_carriers', ['shipping_carrier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_shipping_carrier', type_='foreignkey')
        batch_op.drop_constraint('fk_order_shipping_method', type_='foreignkey')
        batch_op.drop_column('shipping_method_id')
        batch_op.drop_column('shipping_carrier_id')

    op.drop_table('shipping_quotes')
    op.drop_table('shipping_methods')
    op.drop_table('shipping_carriers')
    # ### end Alembic commands ###
