"""Add shipping carrier and method to orders table

Revision ID: 59b0a93df9fb
Revises: d11f265e9d06
Create Date: 2024-12-13 01:22:12.112735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b0a93df9fb'
down_revision = 'd11f265e9d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_carrier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_method_id', sa.Integer(), nullable=True))
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_order_shipping_method', 'shipping_methods', ['shipping_method_id'], ['id'])
        batch_op.create_foreign_key('fk_order_shipping_carrier', 'shipping_carriers', ['shipping_carrier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_shipping_carrier', type_='foreignkey')
        batch_op.drop_constraint('fk_order_shipping_method', type_='foreignkey')
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('shipping_method_id')
        batch_op.drop_column('shipping_carrier_id')

    # ### end Alembic commands ###
