"""Add stripe_payment_id to orders with named constraint

Revision ID: 8e53d4f7833d
Revises: adc2a3716b03
Create Date: 2024-11-27 12:02:34.545168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e53d4f7833d'
down_revision = 'adc2a3716b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_order_stripe_payment_id', ['stripe_payment_id'])
        batch_op.create_unique_constraint(None, ['stripe_payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_order_stripe_payment_id', type_='unique')
        batch_op.drop_column('stripe_payment_id')

    # ### end Alembic commands ###
