"""Add shipping fields to Order model

Revision ID: a91a2f3aa387
Revises: 87e1bfadc616
Create Date: 2024-12-12 02:08:52.689261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91a2f3aa387'
down_revision = '87e1bfadc616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_tracking_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_order_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pickup_order_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_status_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_estimated_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_estimated_date')
        batch_op.drop_column('delivery_updated_at')
        batch_op.drop_column('delivery_created_at')
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('delivery_status_code')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('pickup_order_id')
        batch_op.drop_column('delivery_order_id')
        batch_op.drop_column('delivery_tracking_number')

    # ### end Alembic commands ###
