"""Add address fields for Bosta shipping

Revision ID: d11f265e9d06
Revises: 58c649cf7f5e
Create Date: 2024-12-13 00:33:34.662569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11f265e9d06'
down_revision = '58c649cf7f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('building_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('apartment', sa.String(length=10), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_carrier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_method_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shipping_carriers', ['shipping_carrier_id'], ['id'])
        batch_op.create_foreign_key(None, 'shipping_methods', ['shipping_method_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipping_method_id')
        batch_op.drop_column('shipping_carrier_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('apartment')
        batch_op.drop_column('floor')
        batch_op.drop_column('building_number')
        batch_op.drop_column('street2')

    # ### end Alembic commands ###
