"""Add cancelled_by to orders

Revision ID: ebf5b354cc58
Revises: 9d7aa5660f29
Create Date: 2024-11-27 02:05:43.989659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf5b354cc58'
down_revision = '9d7aa5660f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('cancelled_by')

    # ### end Alembic commands ###
